#!/bin/sh

#  pre-build.sh
#  Potori
#
#  Created by Lucka on 16/1/2021.
#  
cd "${PROJECT_DIR}"

GIT_COMMIT_COUNT=$(git rev-list --count HEAD)

INFO_PLIST_PREPROCESS_FILE="Shared/info_plist_preprocessor.h"

echo "//---------------------------------------------------------------"    > $INFO_PLIST_PREPROCESS_FILE
echo "// Automatically generated by pre-build.sh. Do NOT edit manually."    >> $INFO_PLIST_PREPROCESS_FILE
echo "//---------------------------------------------------------------"    >> $INFO_PLIST_PREPROCESS_FILE
echo ""                                                                     >> $INFO_PLIST_PREPROCESS_FILE
echo "#define GIT_COMMIT_COUNT ${GIT_COMMIT_COUNT}"                         >> $INFO_PLIST_PREPROCESS_FILE
