name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    name: Build and Test macOS Scheme
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build for Testing
        run: build-for-testing -scheme macOS
      - name: Test
        run: xcodebuild test-without-building -scheme macOS
